# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48c753f055503f3df00ff86e696cc3d0c5a61d40f3370727b5c4188be91331061353e91d666f8362b0e25792724da50653f821e1deefc61d3e62774789f31f40

test:
  secret_key_base: be6a777dc74f9b61e8aa718d98dc20bbae6ff6c2d5e7d3eed4dba093a3d5df6c4cbb6d97fb3f22f082598c91fbefe117dbc4787695fb0c8c3eaeb8e85f395114

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
